class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start5'
        self.MirrorCommand = 'mirror5'
        self.UnzipMirrorCommand = 'unzipmirror5'
        self.TarMirrorCommand = 'tarmirror5'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall5'
        self.ListCommand = 'list141'
        self.StatusCommand = 'status'
        self.AuthorizeCommand = 'authorize5'
        self.UnAuthorizeCommand = 'unauthorize5'
        self.PingCommand = 'ping5'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help45546456'
        self.LogCommand = 'log5'
        self.SpeedCommand = 'speedtest5'
        self.CloneCommand = 'clone5'
        self.WatchCommand = 'watch5'
        self.TarWatchCommand = 'tarwatch5'
        self.DeleteCommand = 'd'
        self.UsageCommand = 'usage5'
        self.RepoCommand = 'repo0025'

BotCommands = _BotCommands()
